/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import modelo.Libro;

/**
 *
 * @author usuario
 */
public class PanelDatosLibro extends javax.swing.JPanel {

    /**
     * Creates new form PanelDatosLibro
     */
    public PanelDatosLibro() {
        initComponents();
    }
    
    public Libro getLibro(){
        Libro libro = new Libro(jtISBN.getText().trim(),jtTitulo.getText().trim(),jtAutor.getText());
        return libro; 
    }
    
    public void refresh(){
        jtISBN.setText("");
        jtTitulo.setText("");
        jtAutor.setText("");
    }
    
    public boolean getStateOfJTF(){
        if(!jtISBN.getText().equals("") && !jtTitulo.getText().equals("") && !jtAutor.getText().equals("")){
            return true;
        }
    return false;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlISBN = new javax.swing.JLabel();
        jlTitulo = new javax.swing.JLabel();
        jlAutor = new javax.swing.JLabel();
        jtISBN = new javax.swing.JTextField();
        jtTitulo = new javax.swing.JTextField();
        jtAutor = new javax.swing.JTextField();

        jlISBN.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jlISBN.setText("ISBN:");

        jlTitulo.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jlTitulo.setText("Título:");

        jlAutor.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jlAutor.setText("Autor:");

        jtISBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtISBNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlISBN)
                            .addComponent(jlTitulo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlAutor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtAutor)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlISBN)
                    .addComponent(jtISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlTitulo)
                    .addComponent(jtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlAutor)
                    .addComponent(jtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtISBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtISBNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtISBNActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlAutor;
    private javax.swing.JLabel jlISBN;
    private javax.swing.JLabel jlTitulo;
    private javax.swing.JTextField jtAutor;
    private javax.swing.JTextField jtISBN;
    private javax.swing.JTextField jtTitulo;
    // End of variables declaration//GEN-END:variables
}
